### ISSUE TITLE
Suggestion: Add keyboard layout display

### ISSUE THREAD

**Issue by Lassebq** [ErikReider/SwayOSD#38] opened 2023-08-02 18:17 UTC
Not sure if it's possible using libinput backend, but if it isn't, please add custom message support, so you could do `swayosd --custom $(compositor specific command to get current keyboard layout)`

**Comment by ErikReider** [comment] 2023-08-02 22:57
A custom osd type would be the way to go.

Duplicate of #24

**Closed by ErikReider** 2023-08-02 22:57 UTC
